In [5]:
import numpy as np

In [79]:
# Left and right, simply check greedily when we get to the row

visibility_grid = []
tallest_in_column_so_far = []
rows = []


with open('input.txt') as file:
    current_row = -1
    # Just store everything in a matrix and then solve it...
    for f in file:
        current_row += 1
        row_values = [int(i) for i in f.strip()]
        rows.append(row_values)
        
    visibility_grid = np.zeros((current_row + 1, len(row_values)))
    
    
    for row_num, row_vals in enumerate(rows):
        largest_so_far = -1
        for col_num, col_val in enumerate(row_vals):
            if col_val > largest_so_far:
                visibility_grid[row_num, col_num] = 1
                largest_so_far = col_val
                
    for row_num, row_vals in enumerate(rows):
        largest_so_far = -1
        for col_num in range(len(row_vals) -1, -1, -1):
            col_val = row_vals[col_num]
            if col_val > largest_so_far:
                visibility_grid[row_num, col_num] = 1
                largest_so_far = col_val
                
    for col_num in range(len(f.strip())):
        largest_so_far = -1
        for row_num in range(len(rows)):
            col_val = rows[row_num][col_num]
            if col_val > largest_so_far:
                visibility_grid[row_num, col_num] = 1
                largest_so_far = col_val
                
    for col_num in range(len(f.strip())):
        largest_so_far = -1
        for row_num in range(len(rows) -1, -1, -1):
            col_val = rows[row_num][col_num]
            if col_val > largest_so_far:
                visibility_grid[row_num, col_num] = 1
                largest_so_far = col_val
        
print(visibility_grid)
# For seeing from the top: keep a list of the tallest encountered in each column - if taller than current, then it is now visible

total_visible = np.sum(visibility_grid)
print(total_visible)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 ...
 [1. 0. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
1543.0


In [99]:
# Left and right, simply check greedily when we get to the row

visibility_grid = []
tallest_in_column_so_far = []
rows = []


with open('input.txt') as file:
    current_row = -1
    # Just store everything in a matrix and then solve it...
    for f in file:
        current_row += 1
        row_values = [int(i) for i in f.strip()]
        rows.append(row_values)
        
    scenic_scores = np.ones((current_row + 1, len(row_values)))
    for row_num, row_vals in enumerate(rows):
        # Create a dict to store the how far each height of tree can see
        far_dict = {i: 0 for i in range(0,10)}
        for col_num in range(1, len(row_vals)):
            col_val = row_vals[col_num]
            can_see_to = far_dict[col_val]
            dist = col_num - can_see_to
            scenic_scores[row_num][col_num] *= dist
            for i in range(0, col_val + 1):
                far_dict[i] = col_num
                
    for row_num, row_vals in enumerate(rows):
        far_dict = {i: len(row_vals) - 1 for i in range(0,10)}
        for col_num in range(len(row_vals) -2, -1, -1):
            col_val = row_vals[col_num]
            can_see_to = far_dict[col_val]
            dist = can_see_to - col_num
            scenic_scores[row_num][col_num] *= dist
            for i in range(0, col_val + 1):
                far_dict[i] = col_num
    
    for col_num in range(len(f.strip())):
        far_dict = {i: 0 for i in range(0,10)}
        for row_num in range(1, len(rows)):
            col_val = rows[row_num][col_num]
            can_see_to = far_dict[col_val]
            dist = row_num - can_see_to
            scenic_scores[row_num][col_num] *= dist
            for i in range(0, col_val + 1):
                far_dict[i] = row_num
                

    for col_num in range(len(f.strip())):
        far_dict = {i: len(rows) - 1 for i in range(0,10)}
        for row_num in range(len(rows) -2, -1, -1):
            col_val = rows[row_num][col_num]
            can_see_to = far_dict[col_val]
            dist = can_see_to - row_num
            scenic_scores[row_num][col_num] *= dist
            for i in range(0, col_val + 1):
                far_dict[i] = row_num
        

print(scenic_scores)
print(np.max(scenic_scores))
print(np.max([i[1:-1] for i in scenic_scores[1:-1]]))

[[ 6.  4.  3. ...  4.  5.  1.]
 [ 3.  1.  4. ...  1.  3. 45.]
 [48. 12.  1. ...  6.  4.  2.]
 ...
 [ 2.  4.  2. ...  4.  4.  1.]
 [ 1.  2.  1. ...  1.  3.  1.]
 [ 2.  4.  2. ...  1.  1. 20.]]
595080.0
595080.0


In [97]:
np.max([i[1:-1] for i in scenic_scores[1:-1]])

8.0